geeksshop/baskats/urls.py
from django.urls import path


from .views import basket_add, basket_remote, basket_edit


app_name = 'baskets'

urlpatterns = [
    path('add/<int:product_id>/', basket_add, name='basket_add'),
    path('remove/<int:product_id>/', basket_remote, name='basket_remote'),
    path('edit/<int:id>/<int:quantity>/', basket_edit, name='basket_edit'),
]

geeksshop/geeksshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar
from products.views import index




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls'), name='products'),
    path('users/', include('users.urls'), name='users'),
    path('baskets/', include('baskats.urls'), name='baskets'),
    path('admins/', include('admins.urls'), name='admins'),
    path('', include('social_django.urls'), name='social'),
    path('orders/', include('orderapp.urls'), name='orders'),
    path('^__debug_/', include(debug_toolbar.urls))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geeksshop/orderapp/urls.py
from django.urls import path, include
from .views import OrderList, OrderCreate, OrderDelete, OrderDetail, OrderUpdate, order_forming_complete, add_pro


app_name = 'orders'

urlpatterns = [
    path('', OrderList.as_view(), name='list'),
    path('create/', OrderCreate.as_view(), name='create'),
    path('update/<int:pk>/', OrderUpdate.as_view(), name='update'),
    path('read/<int:pk>/', OrderDetail.as_view(), name='read'),
    path('delete/<int:pk>/', OrderDelete.as_view(), name='delete'),
    path('forming_complete/<int:pk>/', order_forming_complete, name='forming_complete'),
    path('add_pro/<int:id>/', add_pro, name='add_pro'),

]

geeksshop/users/urls.py
from django.urls import path



from .views import LoginListView, RegisterListView, ProfileFormView, RegisterListView, Logout, verify

app_name = 'users'

urlpatterns = [
    path('login/', LoginListView.as_view(), name='login'),
    path('register/', RegisterListView.as_view(), name='register'),
    path('logout/', Logout.as_view(), name='logout'),
    path('profile/', ProfileFormView.as_view(), name='profile'),

    path('verify/<str:email>/<str:activation_key>/', verify, name='verify')

]

geeksshop/baskats/models.py
from django.db import models

from users.models import User
from products.models import Products

# class BasketsQuerySet(models.QuerySet):
#
#     def delete(self, *args, **kwargs):
#         for item in self:
#             item.products.quantity += item.quantity
#             item.products.save()
#         super(BasketsQuerySet, self).delete()



class Basket(models.Model):
    # objects = BasketsQuerySet.as_manager()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    products = models.ForeignKey(Products, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    update_timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Корзина для {self.user.username} | Продукт {self.products.products_name}'

    def sum(self):
        return self.quantity * self.products.products_price

    def sum_sale(self):
        return self.quantity * self.products.total_price()

    def total_quantity(self):
        baskets = Basket.objects.filter(user=self.user)
        total = 0
        for basket in baskets:
            total += basket.quantity
        return total

    def total_sum(self):
        baskets = Basket.objects.filter(user=self.user)
        sum = 0
        for basket in baskets:
            sum += basket.sum()
        return sum

    def total_sum_sale(self):
        baskets = Basket.objects.filter(user=self.user)
        sum = 0
        for basket in baskets:
            sum += basket.sum_sale()
        return sum
    
    # def delete(self, using=None, keep_parents=False):
    #     self.products.quantity += self.quantity
    #     self.products.save()
    #     super(Basket, self).delete()
    #
    # def save(self, force_insert=False, force_update=False, using=None,
    #          update_fields=None):
    #     print(1)
    #     if self.pk:
    #         print(2)
    #         self.products.quantity += self.quantity - self.get_item(int(self.pk))
    #     else:
    #         print(3)
    #         self.products.quantity -= self.quantity
    #     self.products.save()
    #     super(Basket, self).save()


    @staticmethod
    def get_item(pk):
        return Basket.objects.get(pk=pk).quantity

geeksshop/baskats/views.py
from django.db.models import F
from django.shortcuts import render
from django.shortcuts import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.template.loader import render_to_string

from products.models import Products
from .models import Basket


@login_required
def basket_add(request, product_id):
    product = Products.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, products=product)
    if request.is_ajax():
        if not baskets.exists():
            Basket.objects.create(user=request.user, products=product, quantity=1)
        else:
            basket = baskets.first()
            basket.quantity = F('quantity') + 1
            basket.save()
    else:
        if not baskets.exists():
            Basket.objects.create(user=request.user, products=product, quantity=1)
        else:
            basket = baskets.first()
            basket.quantity = F('quantity') + 1
            basket.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_remote(request, product_id):
    Basket.objects.get(id=product_id).delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_edit(request, id, quantity):
    if request.is_ajax():
        basket = Basket.objects.get(id=id)
        if quantity > 0:
            basket.quantity = quantity
            basket.save()
        else:
            basket.delete()

        baskets = Basket.objects.filter(user=request.user)
        context = {
            'baskets': baskets
        }
        result = render_to_string('baskets/backets.html', context)
        return JsonResponse({'result': result})

geeksshop/baskats/templates/baskets/backets.html
<div class="basket_list">

    {% if baskets %}
        <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
            Корзина <span class="badge badge-secondary badge-pill">{{ baskets.first.total_quantity }}</span>
        </h4>
        {% for basket in baskets %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ basket.products }}</h5>
                    <p class="card-text">{{ basket.products.products_descriptions }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item bg-light">
                        <div class="row text-center">
                            <div class="col-lg-4">
                                <input name="{{ basket.id }}" type="number" class="form-control"
                                       value="{{ basket.quantity }}" min="0">
                            </div>
                            <div class="col-lg-4">{{ basket.sum }} руб.</div>
                            <div class="col-lg-4">
                                <a href="{% url 'baskets:basket_remote' basket.id %}">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </div>

                        </div>
                    </li>
                </ul>
                <div class="card-body">Скидка {{ basket.products.total_sale }} %</div>
            </div>
        {% endfor %}
        <div class="card mb-3">
            <div class="card-footer">
                <p class="float-left">Итого</p>
                <h4 class="float-right">{{ baskets.first.total_sum }} руб.</h4>
            </div>
            <div class="card-footer" style="background-color: lightpink">
                <p class="float-left">Со скидкой</p>
                <h4 class="float-right" style="color: red">{{ baskets.first.total_sum_sale }} руб.</h4>

            </div>
        </div>
        <a href="{% url 'orders:create' %}">
        <button type="button" class="btn btn-success btn-lg float-right">Оформить</button>
        </a>
    {% else %}
        <h4 class="mt-3 mb-3 text-center"> Корзина пуста </h4>
    {% endif %}

</div>