geeksshop/geeksshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar
from products.views import index




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls'), name='products'),
    path('users/', include('users.urls'), name='users'),
    path('baskets/', include('baskats.urls'), name='baskets'),
    path('admins/', include('admins.urls'), name='admins'),
    path('', include('social_django.urls'), name='social'),
    path('orders/', include('orderapp.urls'), name='orders'),
    path('^__debug_/', include(debug_toolbar.urls))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geeksshop/orderapp/urls.py
from django.urls import path, include
from .views import OrderList, OrderCreate, OrderDelete, OrderDetail, OrderUpdate, order_forming_complete, add_pro


app_name = 'orders'

urlpatterns = [
    path('', OrderList.as_view(), name='list'),
    path('create/', OrderCreate.as_view(), name='create'),
    path('update/<int:pk>/', OrderUpdate.as_view(), name='update'),
    path('read/<int:pk>/', OrderDetail.as_view(), name='read'),
    path('delete/<int:pk>/', OrderDelete.as_view(), name='delete'),
    path('forming_complete/<int:pk>/', order_forming_complete, name='forming_complete'),
    path('add_pro/<int:id>/', add_pro, name='add_pro'),

]

geeksshop/users/urls.py
from django.urls import path



from .views import LoginListView, RegisterListView, ProfileFormView, RegisterListView, Logout, verify

app_name = 'users'

urlpatterns = [
    path('login/', LoginListView.as_view(), name='login'),
    path('register/', RegisterListView.as_view(), name='register'),
    path('logout/', Logout.as_view(), name='logout'),
    path('profile/', ProfileFormView.as_view(), name='profile'),

    path('verify/<str:email>/<str:activation_key>/', verify, name='verify')

]

geeksshop/orderapp/models.py
from django.db import models

# Create your models here.
from django.db.models.signals import pre_delete, pre_save
from django.dispatch import receiver

from geeksshop import settings
from products.models import Products

from baskats.models import Basket


class Order(models.Model):

    FORMING = 'FM'
    SEND_TO_PROCEED = 'STP'
    PAID = 'PD'
    PROCEEDED = 'PRO'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SEND_TO_PROCEED, 'отправлен в обработку'),
        (PAID, 'оплачено'),
        (PROCEEDED, 'обрабатывается'),
        (READY, 'готову выдаче'),
        (CANCEL, 'отмена заказа'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    update = models.DateTimeField(verbose_name='обновлен', auto_now=True)
    status = models.CharField(choices=ORDER_STATUS_CHOICES, verbose_name='статус', max_length=3, default=FORMING)
    is_active = models.BooleanField(verbose_name='активный', default=True)

    def __str__(self):
        return f'Текущий заказ {self.pk}'

    def get_total_quantity(self):
        items = self.order_items.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_total_cost(self):
        items = self.order_items.select_related()
        # print(self.order_items)
        return sum(list(map(lambda x: x.get_product_cost(), items)))

    def get_items(self):
        pass

    def delete(self, using=None, keep_parents=False, num=None):

        for item in self.order_items.select_related():
            item.products.quantity += item.quantity

            item.save()
        self.is_active = True
        self.save()

        def get_summary(self):
            items = self.order_items.select_related()
            return {
            'get_total_cost': sum(list(map(lambda x: x.get_product_cost(), items))),
            'get_total_quantity': sum(list(map(lambda x: x.quantity, items)))}

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='order_items', on_delete=models.CASCADE)
    product = models.ForeignKey(Products, verbose_name='продукты', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)


    def get_product_cost(self):
        return self.product.products_price * self.quantity

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.get(pk=pk).quantity

@receiver(pre_delete, sender=Basket)
@receiver(pre_delete, sender=OrderItem)
def product_quantity_update_delete(sender, instance, **kwargs):
    instance.product.quantity += instance.quantity
    instance.save()


@receiver(pre_save, sender=Basket)
@receiver(pre_save, sender=OrderItem)
def product_quantity_update_delete(sender, instance, **kwargs):
    if instance.pk:
        # print(1, instance, type(instance))
        instance.product.quantity = instance.quantity - instance.get_item(int(instance.pk))
        instance.product.save()
    else:
        # print(2)
        instance.products.quantity -= instance.quantity
        instance.products.save()

geeksshop/orderapp/forms.py
from django import forms
from .models import Order, OrderItem

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class OrderItemsForm(forms.ModelForm):

    price = forms.CharField(label='цена', required=False)

    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(OrderItemsForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class StatusForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('status',)

    def __init__(self, *args, **kwargs):
        super(StatusForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

geeksshop/orderapp/views.py
from django.db import transaction
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
# Create your views here.

from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from orderapp.models import Order, OrderItem
from geeksshop.mixin import BaseClassContextMixin
from orderapp.forms import OrderItemsForm
from baskats.models import Basket

from products.models import Products


class OrderList(ListView):
    model = Order

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user, is_active=True)


class OrderCreate(CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy('orders:list')
    # context_object_name = object

    def get_context_data(self, **kwargs):
        context = super(OrderCreate, self).get_context_data(**kwargs)
        context['title'] = 'Создать заказ'
        context['price'] = None


        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemsForm, extra=1)
        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            basket_items = Basket.objects.filter(user=self.request.user)
            if basket_items:
                OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemsForm, extra=basket_items.count())
                formset = OrderFormSet()

                for num, form in enumerate(formset.forms):

                    form.initial['product'] = basket_items[num].products
                    form.initial['quantity'] = basket_items[num].quantity
                    form.initial['price'] = basket_items[num].products.products_price
                basket_items.delete()

            else:
                formset = OrderFormSet()
        context['order_items'] = formset
        return context


    def form_valid(self, form):
        context = self.get_context_data()
        order_items = context['order_items']


        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if order_items.is_valid():
                order_items.instance = self.object
                order_items.instance.save()

            if self.object.get_total_cost() == 0:
                print(1)
                self.object.delete()

        return super(OrderCreate, self).form_valid(form)


class OrderUpdate(UpdateView):
    model = Order
    fields = []
    success_url = reverse_lazy('orders:list')


    def get_context_data(self, **kwargs):
        context = super(OrderUpdate, self).get_context_data(**kwargs)
        context['title'] = 'Обновление заказа'

        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemsForm, extra=1)
        if self.request.POST:
            formset = OrderFormSet(self.request.POST, instance=self.object)
        else:

            formset = OrderFormSet(instance=self.object)
            for form in formset:
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.products_price
        context['order_items'] = formset
        return context


    def form_valid(self, form):
        context = self.get_context_data()
        order_items = context['order_items']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if order_items.is_valid():
                order_items.instance = self.object
                order_items.instance.save()

            if self.object.get_total_cost() == 0:
                self.object.delete()

        return super(OrderUpdate, self).form_valid(form)


class OrderDelete(DeleteView):
    model = Order
    success_url = reverse_lazy('orders:list')


class OrderDetail(DetailView, BaseClassContextMixin):
    model = Order
    title = 'Просмотр заказа'


def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SEND_TO_PROCEED
    order.save()
    return HttpResponseRedirect(reverse('orders:list'))

def status(request, status, order_id):
    '''не завершено, обновление статуса в заказах'''
    pass

def add_pro(request, id):
    '''не завершено, последняя строка товаров в заказе.'''
    price = Products.objects.get(id=id).products_price
    return HttpResponse(price)

geeksshop/orderapp/templates/orderapp/order_confirm_delete.html
{% extends 'products/base.html' %}
{% load static %}

{% block content %}
    <div class="text-center">
        <div class="category_delete">
            <div class="h1">Уверены, что хотите удалить?</div>
            {% include 'orderapp/includes/inc_order_summary.html' %}
            <form action="{% url 'orders:delete' object.pk %}" method="post">
                {% csrf_token %}
                <input class="btn btn-danger" type="submit" value="удалить">
            </form>
            <button class="btn btn-success mt-4">
                <a href="{% url 'orders:list' %}">отмена</a>
            </button>
        </div>
    </div>
{% endblock %}

geeksshop/orderapp/templates/orderapp/order_detail.html
{% extends "products/base.html" %}
{% load static %}

{% block content %}
    {% include 'orderapp/includes/inc_order_summary.html' %}
    <div class="basket_list">
        {% for item in object.orderitems.select_related %}
            <div class="basket_record">
                <img style="height: 150px" src="{{ item.product.image.url }}"
                     alt="{{ item.product.short_desc }}">
                <span class="category_name">
                   {{ item.product.category.name }}
               </span>
                <span class="product_name">{{ item.product.name }}</span>
                <span class="product_price">
                   {{ item.product.price }}&nbspруб
               </span>
                <span class="product_quantitiy">
                   x {{ item.quantity }} шт.
               </span>
                <span class="product_cost">
                    = {{ item.get_product_cost }}&nbspруб
               </span>
            </div>
        {% endfor %}
    </div>
    {% include 'orderapp/includes/inc_order_actions.html' %}

{% endblock %}

geeksshop/orderapp/templates/orderapp/order_form.html
{% extends "products/base.html" %}
{% load static %}
{% load cache %}

{% block content %}
    {% include 'orderapp/includes/inc_order_summary.html' %}
    <div class="order_form">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <table class="table">
                {{ order_items.management_form }}
                {% for form in order_items.forms %}
                    {% if forloop.first %}
                        <thead>
                        <tr>
                            {% for field in form.visible_fields %}
                                <th class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                    {{ field.label|capfirst }}
                                </th>
                            {% endfor %}
                        </tr>
                        </thead>
                    {% endif %}
                    <tr class="formset_row">
                        {% for field in form.visible_fields %}
                            <td class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                {% if forloop.first %}
                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                {% endif %}
                                {{ field.errors.as_ul }}


                                {% if field.name == 'price' %}
                                    {% if not field.value %}
                                    {% else %}
                                        <span class="orderitems-{{ forloop.parentloop.counter0 }}-price">
                                            {{ field.value}} руб </span>
                                    {% endif %}
                                {% else %}
                                    {{ field }}
                                {% endif %}


                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
            <button type="submit" value="сохранить" class="btn btn-default btn-round form-control last">сохранить
            </button>
            {% include 'orderapp/includes/inc_order_actions.html' %}
        </form>
    </div>

{% endblock %}

geeksshop/orderapp/templates/orderapp/order_list.html
{% extends 'products/base.html' %}
{% load static %}


{% block content %}

    <div class="text-center">
        <div class="h2 text-center head">
            Ваши заказы,
            {% if user.first_name %}
                {{ user.first_name|title }}
            {% else %}
                Пользователь
            {% endif %}
        </div>
        <style>
            .dropdown {
                position: relative;
                display: inline-block;
            }

            /* Выпадающее содержимое (скрыто по умолчанию) */
            .dropdown-content {
                display: none;
                position: absolute;
                background-color: #f1f1f1;
                min-width: 160px;
                box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
                z-index: 1;
            }

            /* Ссылки внутри выпадающего списка  */
            .dropdown-content a {
                color: black;
                padding: 12px 16px;
                text-decoration: none;
                display: block;
            }

            /* Изменение цвета выпадающих ссылок при наведении курсора */
            .dropdown-content a:hover {background-color: deepskyblue}

            /* Показать выпадающее меню */
            .show {display:block;}
        </style>
        <table class="table orders_list">
            <thead>
            <tr>
                <th>ID</th>
                <th>Создан</th>
                <th>Обновлен</th>
                <th>Статус</th>
                <th></th>
                <th></th>
                <th></th>
                <th>Изменить статус заказа</th>
            </tr>
            </thead>
            <tbody>
            {% for item in object_list %}
                {% if item.is_active %}
                    <tr>
                        <td class="td1 orders_list">{{ item.pk }}</td>
                        <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                        <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                        <td>{{ item.get_status_display }}</td>
                        <td>
                            <a href="{% url 'orders:read' item.pk %}">
                                посмотреть
                            </a>
                        </td>
                        <td>
                            {% if item.status == 'FM' %}
                                <a href="{% url 'orders:update' item.pk %}">
                                    редактировать
                                </a>
                            {% endif %}
                        </td>

                        <td>
                            {% if item.status == 'FM' %}
                                <a href="{% url 'orders:delete' item.pk %}">
                                    удалить
                                </a>
                            {% endif %}
                        </td>
                        <td>
                            {% if item.status == 'FM' %}
                                <div class="dropdown">
                                <button onclick="myFunction()" class="btn btn-light btn-round">Изменить</button>
                                <div id="myDropdown" class="dropdown-content">
                                        {% for s in status %}
                                            <a href="" name="{{ item.pk }}">{{ s.1 }}</a>
                                        {% endfor %}
                                </div>
                                </div>

                            {% endif %}
                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>

        <button class="btn btn-light btn-round">
            <a href="{% url 'index' %}">
                на главную
            </a>
        </button>
        <button class="btn btn-warning btn-round">
            <a href="{% url 'orders:create' %}">
                новый
            </a>
        </button>
    </div>
    <script>

        function myFunction() {
            document.getElementById("myDropdown").classList.toggle("show");
        }

    </script>
{% endblock %}