geeksshop/admins/urls.py
from django.urls import path

from .views import index, UserListView, UserUpdateView, UserCreateView, UserDeleteView, CategoryCreateView, \
    CategoryUpdateView, CategoryDeleteView, CategoryListView, ProductsAdminListView, ProductsAdminCreateView, \
    ProductsAdminUpdateView, ProductsAdminDeleteView



app_name = 'admins'

urlpatterns = [
    path('', index, name='index'),
    path('users/', UserListView.as_view(), name='admins_user'),
    path('users-create/', UserCreateView.as_view(), name='admins_user_create'),
    path('users-update/<int:pk>/', UserUpdateView.as_view(), name='admins_user_update'),
    path('users-delete/<int:pk>', UserDeleteView.as_view(), name='admins_user_delete'),
    path('categories/', CategoryListView.as_view(), name='category_list_view'),
    path('category-create/', CategoryCreateView.as_view(), name='category_create'),
    path('category-update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category-delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),
    path('products/', ProductsAdminListView.as_view(), name='products_list_view'),
    path('products-create/', ProductsAdminCreateView.as_view(), name='products_create'),
    path('products-update/<int:pk>/', ProductsAdminUpdateView.as_view(), name='products_update'),
    path('products-delete/<int:pk>/', ProductsAdminDeleteView.as_view(), name='products_delete'),


]

geeksshop/baskats/urls.py
from django.urls import path


from .views import basket_add, basket_remote, basket_edit


app_name = 'baskets'

urlpatterns = [
    path('add/<int:product_id>/', basket_add, name='basket_add'),
    path('remove/<int:product_id>/', basket_remote, name='basket_remote'),
    path('edit/<int:id>/<int:quantity>/', basket_edit, name='basket_edit'),
]

geeksshop/geeksshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar
from products.views import index




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls'), name='products'),
    path('users/', include('users.urls'), name='users'),
    path('baskets/', include('baskats.urls'), name='baskets'),
    path('admins/', include('admins.urls'), name='admins'),
    path('', include('social_django.urls'), name='social'),
    path('orders/', include('orderapp.urls'), name='orders'),
    path('^__debug_/', include(debug_toolbar.urls))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geeksshop/orderapp/urls.py
from django.urls import path, include
from .views import OrderList, OrderCreate, OrderDelete, OrderDetail, OrderUpdate, order_forming_complete, add_pro


app_name = 'orders'

urlpatterns = [
    path('', OrderList.as_view(), name='list'),
    path('create/', OrderCreate.as_view(), name='create'),
    path('update/<int:pk>/', OrderUpdate.as_view(), name='update'),
    path('read/<int:pk>/', OrderDetail.as_view(), name='read'),
    path('delete/<int:pk>/', OrderDelete.as_view(), name='delete'),
    path('forming_complete/<int:pk>/', order_forming_complete, name='forming_complete'),
    path('add_pro/<int:id>/', add_pro, name='add_pro'),

]

geeksshop/products/urls.py
from django.urls import path



from .views import index, products, ProductDetail

app_name = 'products'

urlpatterns = [
    path('', products, name='products_url'),
    path('category/<int:category_id>/', products, name='category'),
    path('page/<int:page_id>/', products, name='page'),
    path('product/<int:pk>/<int:cat>', ProductDetail.as_view(), name='product_detail'),
]

geeksshop/users/urls.py
from django.urls import path



from .views import LoginListView, RegisterListView, ProfileFormView, RegisterListView, Logout, verify

app_name = 'users'

urlpatterns = [
    path('login/', LoginListView.as_view(), name='login'),
    path('register/', RegisterListView.as_view(), name='register'),
    path('logout/', Logout.as_view(), name='logout'),
    path('profile/', ProfileFormView.as_view(), name='profile'),

    path('verify/<str:email>/<str:activation_key>/', verify, name='verify')

]

geeksshop/products/models.py
from django.db import models


class CategoryProducts(models.Model):
    name = models.CharField(max_length=50, unique=True, name='category_name')
    description = models.TextField(max_length=200, blank= True, name='category_description')
    active = models.BooleanField(default=True, name='active')
    discont = models.PositiveIntegerField(default=0, name='discont')

    def __str__(self):
        return self.category_name

class Products(models.Model):
    name = models.CharField(max_length=50, name='products_name')
    description = models.TextField(max_length=200, blank=True, name='products_descriptions')
    price = models.DecimalField(max_digits=10, decimal_places=2, name='products_price')
    image = models.ImageField(upload_to='products_image', blank=True)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(CategoryProducts, on_delete=models.CASCADE)
    active = models.BooleanField(default=True, name='active')
    sale = models.PositiveIntegerField(default=0, name='sale')

    # def __init__(self, *args, **kwargs):
    #     super(Products, self).__init__(*args, **kwargs)
    #     if self.category.discont and self.sale:
    #         pass
            # self.products_price = self.total_price()
            # self.save()

    def __str__(self):
        return f'{self.products_name}'

    def total_sale(self):
        return self.sale + self.category.discont

    def total_price(self):
        if self.total_sale():
            return self.products_price - ((self.products_price / 100) * self.total_sale())
        else:
            return self.products_price



# Create your models here.

geeksshop/products/views.py
from django.db.models import Q
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import DetailView

from .models import Products, CategoryProducts


def index(request):
    context = {
        'page_name': 'GeekShop Store',
        'title': 'GeekShop',
        'content': 'Новые образы и лучшие бренды на GeekShop Store.\
                    Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.'
    }
    return render(request, 'products/index.html', context)


def products(request, category_id=None, page_id=1):
    if category_id == None:
        products = Products.objects.filter(active=True)
    else:
        products =Products.objects.filter( Q(category_id=category_id) & Q(active=True))

    paginator = Paginator(products, per_page=6)
    try:
        products_paginator = paginator.page(page_id)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)

    context = {'products': products,
               'categories': CategoryProducts.objects.filter(active=True),
               'title': 'Каталог'}
    context.update({'products': products_paginator})
    return render(request, 'products/products.html', context)



class ProductDetail(DetailView):
    model = Products
    template_name = 'products/product_detail.html'
    context_object_name = 'product'


    def get_context_data(self, category_id=None, *args, **kwargs):
        context = super().get_context_data()

        context['product'] = Products.objects.get(pk=self.kwargs.get('pk'))
        context['categories'] = CategoryProducts.objects.all()
        context['recomm'] = Products.objects.filter(category_id=self.kwargs.get('cat'))
        return context

geeksshop/products/templates/products/add_to_cart.html
    <div class="card h-100">
        <a href="{% url 'products:product_detail' product.id product.category.id %}">
            <img class="card-img-top"
                 src="{{ product.image.url }}"
                 alt="">
        </a>
        <div class="card-body">
            <h4 class="card-title">
                <a href="{% url 'products:product_detail' product.id product.category.id %}">{{ product.products_name }}</a>
            </h4>
            {% if product.total_sale %}
                <h5><s>{{ product.products_price }}</s> <u style="background-color: lightpink; color:red"  >{{ product.total_price }}</u></h5>
            {% else %}
                <h5>{{ product.total_price }}</h5>
            {% endif %}
            <p class="card-text">{{ product.products_descriptions }}</p>
        </div>
        <div class="add-to-cart">
        <div class="card-footer text-center">
            <a href="{% url 'baskets:basket_add' product.id %}"
               class="btn btn-outline-success" name="{{ product.id }}">Отправить в корзину</a>
        </div>
    </div>
</div>

geeksshop/products/templates/products/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/index.css' %}" rel="stylesheet">


</head>

<body>

<!-- Navigation -->
{% block nav %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href={% url 'index' %}>GeekShop</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href={% url 'products:products_url' %}>Каталог <i
                                class="fas fa-shopping-bag"></i> </a>
                    </li>
                    {% if not user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                        </li>
                    {% else %}
{#                        <li class="nav-item">#}
{#                            <a class="nav-link" href="{% url 'users:profile' %}">{{ user.username }}#}
{#                                <i class="fas fa-user-circle"></i>#}
{#                            </a>#}
{#                        </li>#}

                        <li class="nav-item">
                            <div class="dropdown">
                                <a class="nav-link dropdown-toggle" href="" data-toggle="dropdown">
                                    {{ user.username|default:'Пользователь' }}
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="nav-link text-dark" href="{% url 'users:profile' %}">
                                            Профиль
                                        </a>
                                    </li>
                                    <li>
                                        <a class="nav-link text-dark" href="{% url 'orders:list' %}">
                                            Заказы
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admins:index' %}">
                                <i class="fas fa-users-cog"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:logout' %}">Выйти <i
                                    class="fas fa-sign-out-alt"></i></a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

<!-- Page Content -->
{% block content %}{% endblock %}



{% block script %}
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- FontAwesome script -->
    <script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>
{% endblock %}


<script src="{% static 'js/add_to_cart.js' %}"></script>
<script src="{% static 'js/jquery.formset.js' %}"></script>
<script src="{% static 'js/orders_scripts.js' %}"></script>
<script src="{% static 'js/baskets.js' %}"></script>

{% block footer %} {% endblock %}
</body>
</html>

geeksshop/products/templates/products/index.html
{% extends 'products/base.html' %}


{% block title %}{{title|title}}{% endblock %}

<body>

<!-- Navigation -->


<!-- Page Content -->
{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <!-- <h1 class="mt-5">GeekShop Store</h1> -->
                <h1 class="mt-5">{{ page_name }}</h1>
                <p>
                    {{ content }}
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href={% url 'products:products_url' %}>
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>
{% endblock %}

</body>

</html>

geeksshop/products/templates/products/product_detail.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <h1 class="my-4">GeekShop</h1>
                <div class="list-group">
                    <a href="{% url 'products:products_url' %}" class="list-group-item">Все</a>
                </div>
            </div>

            <div class="col-lg-9">
                <div class="row my-5">
                    <div class="card" style="width: 20rem;">
                        <img src="/media/{{ product.image }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{ product.products_name }}</h5>
                            <p class="card-text">{{ product.products_descriptions }}</p>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">
                                {% if product.total_sale %}
                                    <h5><s>{{ product.products_price }}</s> <u
                                            style="background-color: lightpink; color:red">{{ product.total_price }}</u>
                                        руб</h5>
                                {% else %}
                                    <h5>{{ product.total_price }} руб</h5>
                                {% endif %}
                            </li>
                            <li class="list-group-item">
                                {% if product.total_sale %}
                                    <h5>Все скидки на товар:</h5>
                                    {% if product.category.discont %}
                                        <p>1. На категорию "{{ product.category }}" - <u style="background-color: lightpink; color: red"> {{ product.category.discont }}
                                            </u> %</p>
                                    {% endif %}
                                    {% if product.sale %}
                                        <p>2. На данный товар - <u style="background-color: lightpink; color: red"> {{ product.sale }} </u> %</p>
                                    {% endif %}
                                    Итого: <u style="background-color: lightpink; color: red"> {{ product.total_sale }} </u> %
                                {% endif %}
                            </li>
                            <li class="list-group-item">В наличии: {{ product.quantity }}</li>
                        <li class="list-group-item">
                            <div class="card-footer text-center">
                            <a href="{% url 'baskets:basket_add' product.id %}"
                               class="btn btn-outline-success" name="{{ product.id }}">Отправить в корзину</a>
                        </div></li>
                        </ul>
                    </div>
                    <div class="col" >
                        <h4 style="color: cornflowerblue;">Рекомендуемые товары</h4>
                        <div class="container">
                        <div class="row">
                            {% for product_in_category in recomm %}
                            <div class="col">
                            <div class="row my-3">
                                <div class="card">
                                    <a href="{% url 'products:product_detail' product_in_category.id product_in_category.category.id %}">
                                    <img src="{{ product_in_category.image.url }}" class="card-img-top" alt="...">
                                    <div class="card-body">
                                        {% if product_in_category.category.discont or product_in_category.sale %}
                                            <u style="background-color: lightpink; color: red">Sale - {{ product_in_category.total_sale }}</u>
                                            {% else %}
                                            Из категории {{ product_in_category.category }}
                                        {% endif %}
                                    </div>
                                    </a>
                                </div>

                            </div>
                            </div>
                            {% endfor %}

                        </div>
                        </div>
                    </div>
                </div>

            </div>


        </div>
    </div>
{% endblock %}

{% block footer %}
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; GeekShop 2021</p>
        </div>

    </footer>
{% endblock %}

geeksshop/products/templates/products/products.html
{% extends 'products/base.html' %}
{% load static %}

{% block title %}{{ title|title }}{% endblock %}
<!-- <title>GeekShop - Каталог</title> -->

<body>

<!-- Navigation -->

{% block content %}
    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <div class="col-lg-3">

                <h1 class="my-4">GeekShop</h1>
                <div class="list-group">

                    {% for category in categories %}
                        {% if category.active %}
                            <a href="{% url 'products:category' category.id %}"
                               class="list-group-item">{{ category.category_name }}</a>
                        {% endif %}
                    {% endfor %}
                    <a href="{% url 'products:products_url' %}" class="list-group-item">Все товары</a>
                </div>

            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">

                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.jpg' %}"
                                 alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.jpg' %}"
                                 alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.jpg' %}"
                                 alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <div class="row">


                    {% for product in products %}

                        <div class="col-lg-4 col-md-6 mb-4">
                            {% include 'products/add_to_cart.html' %}
                        </div>


                    {% endfor %}

                </div>

                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        <li class="page-item {% if not products.has_previous %} disabled {% endif %} ">
                            <a class="page-link" href="

                                    {% if products.has_previous %}{% url 'products:page' products.previous_page_number %}{% else %} # {% endif %}"
                               tabindex="-1" aria-disabled="true">Предыдущая</a>
                        </li>
                        {% for page in products.paginator.page_range %}
                            <li class="page-item"><a class="page-link"
                                                     href="{% url 'products:page' page %}">{{ page }}</a></li>
                        {% endfor %}

                        <li class="page-item {% if not products.has_next %} disabled {% endif %}">
                            <a class="page-link" href="

                                    {% if products.has_next %}{% url 'products:page' products.next_page_number %}{% else %} # {% endif %}">Следующая</a>
                        </li>
                    </ul>
                </nav>

            </div>

        </div>

    </div>
    <!-- /.container -->
{% endblock %}
<!-- Footer -->
{% block footer %}
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; GeekShop {% now "Y" %}</p>
        </div>
        <!-- /.container -->
    </footer>
{% endblock %}


</body>

</html>